Auto-Update: false
Debug: false
Update-Notifacaitons: true
User-Files: true

Messages:
    Prefix: '&9Customlogin > '
    Login: '&a+ &b(PLAYER)'
    Logout: '&c- &b(PLAYER)'
    Kick: '&c- &b(PLAYER)'
    Ban: '&c- &b(PLAYER)'