Auto-Update: false
Economy-Support: true
Economy-Price: 500
Debug: false
Notify-Updates: true
User-Files: true
Messages:
  Prefix: '&9Customlogin > '
  Login: '&a+ &b(PLAYER)'
  Logout: '&c- &b(PLAYER)'